version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: 'arn:aws:ecs:us-east-1:922538497944:task-definition/frontend:26'
        LoadBalancerInfo:
          ContainerName: 'frontend'
          ContainerPort: 80