apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  template:
    spec:
      initContainers:
      - name: envsub
        image: node
        command: ["sh", "-c"]
        args:
        - envsub /usr/src/app/public/env-config.template.js /usr/src/app/public/env-config.js
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: react-app-config
              key: REACT_APP_API_URL
        volumeMounts:
        - name: app
          mountPath: /usr/src/app
      containers:
      - name: react-app
        image: your-react-app-image
        volumeMounts:
        - name: app
          mountPath: /usr/src/app
      volumes:
      - name: app
        emptyDir: {}