name: Docker Image CI
on: push
defaults:
  run:
    working-directory: frontend
#
jobs:
  build_frontend:
    name: Build frontend docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} |  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build -t mmodi/frontend .
      - name: Push the tagged Docker image
        run: docker push mmodi/frontend
