name: CICD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        working-directory: frontend
      - run: npm start
        working-directory: frontend
      - run: npm test
        working-directory: frontend

      - run: npm install
        working-directory: backend
      - run: npm start
        working-directory: backend
