name: CICD
on:
  push:
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2
      - name: Creating Env variable for front-end
        run: |
          touch ./frontend/.env
          echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> ./frontend/.env
      - name: Creating Env variable for back-end
        run: |
          touch ./backend/.env
          echo DB_PORT=${{ secrets.DB_PORT }} >> ./backend/.env
          echo DB_USER=${{ secrets.DB_USER }} >> ./backend/.env
          echo DB_PASS=${{ secrets.DB_PASS }} >> ./backend/.env
          echo DB_NAME=${{ secrets.DB_NAME }} >> ./backend/.env
      - name: Build full-stack using docker-compose
        run: make run
      - name: Test full-stack
        run: npm test
        