name: Docker Image CI

on: push

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} |  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: frontend - Build tagged Docker image
        run: docker build -t mmodi/frontend .
        working-directory: frontend

      - name: frontend - Push the tagged Docker image
        run: docker push mmodi/frontend

      - name: backend - Build tagged Docker image
        run: docker build -t mmodi/backend .
        working-directory: backend

      - name: backend - Push the tagged Docker image
        run: docker push mmodi/backend
